using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Pipes;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Threading;
using Jumper.Bridge;

namespace JumperBho
{
    // Minimal IObjectWithSite definition - .NET Framework doesn't ship this
    // interop declaration out of the box, so we declare it ourselves. This is
    // THE interface every Browser Helper Object must implement; Trident/MSHTML
    // calls SetSite(browserInstance) when the BHO is loaded into a page, and
    // SetSite(null) when it's being torn down.
    [ComImport]
    [Guid("FC4801A3-2BA9-11CF-A229-00AA003D7352")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IObjectWithSite
    {
        [PreserveSig]
        int SetSite([MarshalAs(UnmanagedType.IUnknown)] object pUnkSite);

        [PreserveSig]
        int GetSite(ref Guid riid, out IntPtr ppvSite);
    }

    // Minimal hand-declared IWebBrowser2 - just enough to read where the
    // browser is currently navigated to (LocationURL) and to know which
    // events fire (DWebBrowserEvents2, declared below). This avoids needing
    // the full Microsoft.mshtml / Interop.SHDocVw type library references for
    // this POC step - we only need a couple of members.
    [ComImport]
    [Guid("D30C1661-CDAF-11d0-8A3E-00C04FC9E26E")]
    [InterfaceType(ComInterfaceType.InterfaceIsIDispatch)]
    public interface IWebBrowser2
    {
        // NOTE: IWebBrowser2's vtable has many members before LocationURL;
        // since this is an IDispatch-based dual interface accessed via COM
        // Interop with named properties (not raw vtable offsets), we can
        // declare just the members we need, in any order, and .NET's COM
        // interop will resolve them via IDispatch::GetIDsOfNames instead of
        // positional vtable matching. This only works because the interface
        // is marked InterfaceIsIDispatch (late-bound), not IUnknown.
        //
        // DISPIDs below are from Microsoft's exdisp.h (DISPID_LOCATIONNAME=210,
        // DISPID_LOCATIONURL=211) - an earlier attempt used 0x64/0x65 (100/101)
        // which are actually DISPID_GOBACK/DISPID_GOFORWARD and caused
        // DISP_E_MEMBERNOTFOUND when invoked as properties.
        [DispId(210)]
        string LocationName { get; }

        [DispId(211)]
        string LocationURL { get; }
    }

    // Standard OLE connection-point interfaces (well-known GUIDs from
    // ocidl.idl) - needed to Advise() our event sink onto the browser's
    // DWebBrowserEvents2 event source, so we get notified AFTER navigation
    // completes (SetSite fires too early - the browser is still blank/
    // about:blank at that instant, confirmed empirically: LocationURL read
    // synchronously inside SetSite came back as "").
    [ComImport]
    [Guid("B196B284-BAB4-101A-B69C-00AA00341D07")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IConnectionPointContainer
    {
        void EnumConnectionPoints(out IntPtr ppEnum);
        void FindConnectionPoint(ref Guid riid, out IConnectionPoint ppCP);
    }

    [ComImport]
    [Guid("B196B286-BAB4-101A-B69C-00AA00341D07")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IConnectionPoint
    {
        void GetConnectionInterface(out Guid pIID);
        void GetConnectionPointContainer(out IConnectionPointContainer ppCPC);
        void Advise([MarshalAs(UnmanagedType.IUnknown)] object pUnkSink, out int pdwCookie);
        void Unadvise(int dwCookie);
        void EnumConnections(out IntPtr ppEnum);
    }

    // DWebBrowserEvents2 - the dispinterface IWebBrowser2 fires events
    // through. We only declare the members we actually need
    // (DocumentComplete and BeforeNavigate2); a dispinterface is
    // invoked strictly by DISPID via IDispatch::Invoke, so declaring a subset
    // is safe - COM never inspects the rest of the interface's members.
    // DISPIDs are from Microsoft's exdisp.h: DISPID_BEFORENAVIGATE2=250 (0xFA)
    // and DISPID_DOCUMENTCOMPLETE=259 (0x103).
    [ComImport]
    [Guid("34A715A0-6587-11D0-924A-0020AFC7AC4D")]
    [InterfaceType(ComInterfaceType.InterfaceIsIDispatch)]
    public interface DWebBrowserEvents2
    {
        [DispId(250)]
        void BeforeNavigate2(
            [MarshalAs(UnmanagedType.IDispatch)] object pDisp,
            ref object URL, ref object flags, ref object targetFrameName,
            ref object postData, ref object headers, ref bool cancel);

        [DispId(259)]
        void DocumentComplete([MarshalAs(UnmanagedType.IDispatch)] object pDisp, ref object URL);

    }

    // Our event sink. Exposed to COM (default IDispatch is auto-generated by
    // .NET for a ComVisible class using ClassInterfaceType.None + explicit
    // interface implementation) so IConnectionPoint.Advise can call back into
    // it by DISPID, matching DWebBrowserEvents2 above.
    [ComVisible(true)]
    [ClassInterface(ClassInterfaceType.None)]
    public class BrowserEventSink : DWebBrowserEvents2
    {
        private readonly Action<string, object, object> _onEvent;

        public BrowserEventSink(Action<string, object, object> onEvent)
        {
            _onEvent = onEvent;
        }

        public void BeforeNavigate2(object pDisp, ref object URL, ref object flags, ref object targetFrameName, ref object postData, ref object headers, ref bool cancel)
        {
            _onEvent("BeforeNavigate2", pDisp, URL);
        }

        public void DocumentComplete(object pDisp, ref object URL)
        {
            _onEvent("DocumentComplete", pDisp, URL);
        }

    }

    // The BHO itself. Step 2: reads LocationURL immediately on SetSite
    // (confirmed too early - browser is still blank at that point), and now
    // additionally Advises a DWebBrowserEvents2 sink so we get
    // BeforeNavigate2/DocumentComplete callbacks with the real URL, to
    // determine whether the browser instance we've been attached to is
    // actually rendering Chameleon content (chsw.tasmc.corp) or something
    // unrelated - step 1's test showed SetSite firing even for what turned
    // out to be an unrelated Windows Explorer WebBrowser-control use, so we
    // need real evidence of which URL(s) this BHO instance actually observes.
    //
    // IMPORTANT: this CLSID must stay in sync with register-bho.ps1's registry
    // entries. If you regenerate this GUID, update the script too.
    [ComVisible(true)]
    [Guid("6B1D4E2A-7F3C-4A9B-9E5D-2C8F1A3B6D71")]
    [ClassInterface(ClassInterfaceType.None)]
    [ProgId("JumperBho.BhoObject")]
    public class BhoObject : IObjectWithSite
    {
        private static readonly string LogPath = @"C:\Temp\jumper-bho.log";
        private IConnectionPoint _connectionPoint;
        private int _adviseCookie;

        private static readonly object _pipeStartLock = new object();
        // ALL browser sites currently alive in this process. Trident creates a
        // BHO instance per browser object (tabs, popups, some frames), so a
        // single static "the" site is wrong - see GetTopWindow for the full
        // root-cause note. Each instance registers its own site here and
        // removes exactly that one on teardown, so one tab closing can no
        // longer blind the bridge to another tab that is still open.
        private static readonly object _sitesLock = new object();
        private static readonly List<object> _liveSites = new List<object>();
        // Mirrors Jumper's HandlePatientsListOpen detection (Chameleon.cs):
        // true when folderFrame currently shows the bare patient list
        // (divHospPatientList exists) AND the Heading frame's "מחלקות"/doctor
        // tab (tdHospDoctor) or nursing tab (tdHospSister) has className
        // "tab_On" - i.e. the user just clicked/landed on that Chameleon tab.
        // Updated on every DocumentComplete; polled by the extension via the
        // named pipe (QUERY_DEPT_TAB) so it can bring the Gecko/modern-app
        // tab to the front, same trigger the real app uses to ShowGecko().
        private static volatile bool _departmentTabActive;
        private static bool _pipeStarted;
        private const string PipeName = BridgeProtocol.PipeName;

        private static void Log(string message)
        {
            try
            {
                var dir = Path.GetDirectoryName(LogPath);
                if (dir != null) Directory.CreateDirectory(dir);
                File.AppendAllText(LogPath, $"{DateTime.Now:O} [pid={System.Diagnostics.Process.GetCurrentProcess().Id}] {message}{Environment.NewLine}");
            }
            catch
            {
                // Never let logging crash the host process - a misbehaving BHO
                // can take down the whole IE-mode tab (or historically, all of
                // Internet Explorer). Fail silently.
            }
        }

        public BhoObject()
        {
            Log("BhoObject constructed (COM activation happened).");
        }

        // This instance's own site, so teardown removes exactly the right one.
        private object _mySite;

        public int SetSite(object pUnkSite)
        {
            if (pUnkSite != null)
            {
                Log($"SetSite(non-null) - BHO is now attached to a browser instance. site type = {pUnkSite.GetType().FullName}");
                _mySite = pUnkSite;
                lock (_sitesLock)
                {
                    if (!_liveSites.Contains(pUnkSite)) _liveSites.Add(pUnkSite);
                    Log($"  -> [sites] Registered site; {_liveSites.Count} live site(s) in this process.");
                }
                TryLogLocation(pUnkSite);
                TryAdviseEvents(pUnkSite);
            }
            else
            {
                Log("SetSite(null) - BHO is being detached/unloaded.");
                // Remove only THIS instance's site. Nulling the shared static
                // unconditionally is what used to break the bridge for every
                // other still-open tab in the process.
                lock (_sitesLock)
                {
                    if (_mySite != null) _liveSites.Remove(_mySite);
                    Log($"  -> [sites] Unregistered site; {_liveSites.Count} live site(s) remain.");
                }
                _mySite = null;
                TryUnadviseEvents();
            }
            return 0; // S_OK
        }

        private static void TryLogLocation(object pUnkSite)
        {
            try
            {
                var web = pUnkSite as IWebBrowser2;
                if (web == null)
                {
                    Log("  -> Site does not expose IWebBrowser2 (or QI failed) - cannot read LocationURL this way.");
                    return;
                }
                string url = null;
                string name = null;
                try { url = web.LocationURL; } catch (Exception ex) { url = $"<error reading LocationURL: {ex.Message}>"; }
                try { name = web.LocationName; } catch (Exception ex) { name = $"<error reading LocationName: {ex.Message}>"; }
                Log($"  -> LocationURL='{url}' LocationName='{name}' (read synchronously at SetSite time - often blank/about:blank; see DocumentComplete events for the real value)");
            }
            catch (Exception ex)
            {
                Log($"  -> TryLogLocation failed: {ex}");
            }
        }

        // A named pipe server ("\\.\pipe\JumperBhoBridge") answers department
        // state queries from the native messaging host. It is only started
        // once THIS process has been
        // confirmed to host the Chameleon FRAMESET (its top document contains
        // 'folderFrame' - see TopDocumentHasFolderFrame). Gating on merely
        // having seen a chsw.tasmc.corp URL is NOT sufficient: every Chameleon
        // popup page runs in its own iexplore.exe and would then race this
        // process for the same pipe name, silently stealing commands it has no
        // frames to execute.
        //
        // Returns true if THIS process's top document is the Chameleon frameset
        // (i.e. it actually contains the 'folderFrame'). Must be called on the
        // UI thread because it touches live COM.
        //
        // ROOT CAUSE this exists to fix (2026-09-09): the pipe was previously
        // started by ANY process that merely saw a chsw.tasmc.corp URL. Every
        // Chameleon popup (FluidBalanceFrm.aspx, MedOrdersFrm.aspx, ...) opens
        // in its own iexplore.exe, each of which qualified and started its own
        // server on the same pipe name. Since PipeServerLoop recreates the
        // server after every client disconnect, whichever process happened to
        // win the next WaitForConnection received the command - frequently a
        // single-page popup process with NO frames at all, producing
        // "Frame 'folderFrame' not found among 0 frame(s)" and an empty
        // GetUserSector(). The bridge was effectively a race between processes.
        private static bool TopDocumentHasFolderFrame()
        {
            try
            {
                return FindFrameWindowByName("folderFrame") != null;
            }
            catch (Exception ex)
            {
                Log($"  -> [pipe-owner] folderFrame check failed: {ex.Message}");
                return false;
            }
        }

        private static void EnsurePipeServerStarted()
        {
            lock (_pipeStartLock)
            {
                if (_pipeStarted) return;
                _pipeStarted = true;
            }
            var thread = new Thread(PipeServerLoop) { IsBackground = true, Name = "JumperBhoPipeServer" };
            thread.Start();
            Log(@"  -> Named pipe server thread started (\\.\pipe\JumperBhoBridge).");
        }

        private static void PipeServerLoop()
        {
            while (true)
            {
                try
                {
                    using (var server = new NamedPipeServerStream(PipeName, PipeDirection.InOut, 1, PipeTransmissionMode.Byte, PipeOptions.None))
                    {
                        server.WaitForConnection();
                        using (var reader = new StreamReader(server))
                        using (var writer = new StreamWriter(server) { AutoFlush = true })
                        {
                            string line = reader.ReadLine();
                            if (!string.IsNullOrWhiteSpace(line))
                            {
                                line = line.Trim();
                                if (string.Equals(line, BridgeProtocol.CmdQueryDeptTab, StringComparison.OrdinalIgnoreCase))
                                {
                                    bool active = _departmentTabActive;
                                    writer.WriteLine(active ? BridgeProtocol.ReplyTrue : BridgeProtocol.ReplyFalse);
                                    Log($"  -> [pipe] Replied to QUERY_DEPT_TAB: {(active ? "1" : "0")}");
                                }
                                else
                                {
                                    Log($"  -> [pipe] Ignored unknown command: {line}");
                                }
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    Log($"  -> [pipe] Pipe server loop error (will retry in 500ms): {ex.Message}");
                    Thread.Sleep(500);
                }
            }
        }

        // Mirrors Jumper's HandlePatientsListOpen (Chameleon.cs lines ~344-397):
        // read-only DOM checks, no navigation/writes - safe to run on every
        // DocumentComplete. Always re-derives everything from the current live
        // site list rather than caching a COM window.
        private static void TryUpdateDepartmentTabState()
        {
            try
            {
                object folderFrameWin = FindFrameWindowByName("folderFrame");
                object headingFrameWin = FindFrameWindowByName("Heading");
                if (folderFrameWin == null || headingFrameWin == null)
                {
                    // Frameset not loaded yet (e.g. still on login page) - not an error.
                    return;
                }

                object folderDoc;
                object headingDoc;
                try
                {
                    folderDoc = InvokeGet(folderFrameWin, "document");
                    headingDoc = InvokeGet(headingFrameWin, "document");
                }
                catch (Exception ex)
                {
                    // Cross-frame document access can transiently fail while a
                    // frame is mid-navigation. Logged distinctly so it is not
                    // confused with a real failure to read the tab state.
                    Log($"  -> [dept-tab] frame document not readable yet: {ex.Message}");
                    return;
                }
                if (folderDoc == null || headingDoc == null) return;

                object patientListEl;
                try
                {
                    patientListEl = folderDoc.GetType().InvokeMember(
                        "getElementById", BindingFlags.InvokeMethod, null, folderDoc, new object[] { "divHospPatientList" });
                }
                catch (Exception ex)
                {
                    Log($"  -> [dept-tab] folderFrame getElementById failed: {ex.Message}");
                    return;
                }
                bool patientListShown = patientListEl != null;

                bool tabOn = false;
                if (patientListShown)
                {
                    tabOn = IsTabOn(headingDoc, "tdHospDoctor") || IsTabOn(headingDoc, "tdHospSister");
                }

                bool newState = patientListShown && tabOn;
                if (newState != _departmentTabActive)
                {
                    // State only - the extension polls it via QUERY_DEPT_TAB and
                    // focuses the Gecko tab itself (background.js
                    // handleDeptTabState). An in-page overlay iframe was tried
                    // and abandoned: Trident renders it, not Chromium, so the
                    // modern app is blank inside it.
                    Log($"  -> [dept-tab] state changed: {_departmentTabActive} -> {newState} (patientListShown={patientListShown}, tabOn={tabOn})");
                }
                _departmentTabActive = newState;
            }
            catch (Exception ex)
            {
                Log($"  -> [dept-tab] TryUpdateDepartmentTabState failed: {ex.Message}");
            }
        }

        private static bool IsTabOn(object doc, string elementId)
        {
            try
            {
                object el = doc.GetType().InvokeMember(
                    "getElementById", BindingFlags.InvokeMethod, null, doc, new object[] { elementId });
                if (el == null) return false;
                object className = el.GetType().InvokeMember("className", BindingFlags.GetProperty, null, el, null);
                return string.Equals(className as string, "tab_On", StringComparison.Ordinal);
            }
            catch
            {
                return false;
            }
        }


        // Small helper around Type.InvokeMember for property-get late binding
        // against a raw COM IDispatch object (System.__ComObject) - this is
        // exactly how VBScript/JScript "obj.Foo" late-bound property access
        // has always worked under the hood, just done explicitly via
        // reflection instead of the compiler doing it for us.
        private static object InvokeGet(object comObject, string memberName)
        {
            return comObject.GetType().InvokeMember(
                memberName, BindingFlags.GetProperty, null, comObject, null);
        }

        private void TryAdviseEvents(object pUnkSite)
        {
            try
            {
                var cpc = pUnkSite as IConnectionPointContainer;
                if (cpc == null)
                {
                    Log("  -> Site does not expose IConnectionPointContainer - cannot subscribe to navigation events.");
                    return;
                }
                var iid = typeof(DWebBrowserEvents2).GUID;
                cpc.FindConnectionPoint(ref iid, out _connectionPoint);
                if (_connectionPoint == null)
                {
                    Log("  -> FindConnectionPoint returned null for DWebBrowserEvents2.");
                    return;
                }
                var sink = new BrowserEventSink((eventName, pDispObj, urlObj) =>
                {
                    Log($"  -> [{eventName}] URL='{urlObj}'");
                    var urlStr = urlObj as string;
                    if (eventName == "DocumentComplete"
                        && urlStr != null
                        && urlStr.IndexOf("chsw.tasmc.corp", StringComparison.OrdinalIgnoreCase) >= 0)
                    {
                        // Only the process hosting the Chameleon FRAMESET may own
                        // the bridge pipe. See EnsurePipeServerStarted for why.
                        // Checked at DocumentComplete because document.frames is
                        // empty until the frameset has actually finished loading.
                        if (TopDocumentHasFolderFrame())
                        {
                            EnsurePipeServerStarted();
                        }
                    }
                    if (eventName == "DocumentComplete")
                    {
                        TryUpdateDepartmentTabState();
                    }
                });
                _connectionPoint.Advise(sink, out _adviseCookie);
                Log($"  -> Advised DWebBrowserEvents2 sink successfully (cookie={_adviseCookie}). Waiting for BeforeNavigate2/DocumentComplete...");
            }
            catch (Exception ex)
            {
                Log($"  -> TryAdviseEvents failed: {ex}");
            }
        }

        private void TryUnadviseEvents()
        {
            try
            {
                if (_connectionPoint != null && _adviseCookie != 0)
                {
                    _connectionPoint.Unadvise(_adviseCookie);
                    Log("  -> Unadvised DWebBrowserEvents2 sink.");
                }
            }
            catch (Exception ex)
            {
                Log($"  -> TryUnadviseEvents failed: {ex}");
            }
            finally
            {
                _connectionPoint = null;
                _adviseCookie = 0;
            }
        }

        public int GetSite(ref Guid riid, out IntPtr ppvSite)
        {
            ppvSite = IntPtr.Zero;
            return unchecked((int)0x80004001); // E_NOTIMPL - we don't need to hand the site back out for this POC
        }

        // Resolves the top-level window that actually hosts the Chameleon
        // frameset in this process.
        //
        // ROOT CAUSE this exists to fix (2026-09-09): _topWebBrowserSite is a
        // STATIC, but Trident creates a BHO instance per browser object in the
        // process (tabs, popups, some frames). Every SetSite(non-null)
        // overwrote it, and SetSite(null) from ANY instance nulled it - even
        // when a different, still-live instance was the real Chameleon
        // frameset. So the bridge worked right after the tab opened and then
        // silently broke the moment any other browser object appeared or went
        // away: web.Document then threw TargetInvocationException, which is
        // what produced the endless "[pipe-owner] folderFrame check failed"
        // and "[dept-tab] ... failed", made patient clicks fall back to
        // "navigate back to list" (tab opens, patient never loads), and left
        // מחלקות stuck reporting inactive.
        //
        // We therefore keep ALL live sites and pick the right one on demand,
        // preferring whichever still exposes folderFrame. Never cached: the
        // correct site changes as tabs come and go.
        private static object GetTopWindow()
        {
            object[] sites;
            lock (_sitesLock)
            {
                sites = _liveSites.ToArray();
            }

            object fallback = null;
            foreach (var site in sites)
            {
                object win = TryGetWindowFromSite(site);
                if (win == null) continue;
                if (WindowHasFrame(win, "folderFrame")) return win;
                if (fallback == null) fallback = win;
            }
            return fallback;
        }

        // Reads site -> Document -> parentWindow, returning null instead of
        // throwing when the browser object is dead or still navigating.
        private static object TryGetWindowFromSite(object site)
        {
            try
            {
                var web = site as IWebBrowser2;
                if (web == null) return null;
                object doc = InvokeGet(web, "Document");
                return doc != null ? InvokeGet(doc, "parentWindow") : null;
            }
            catch
            {
                return null;
            }
        }

        private static bool WindowHasFrame(object win, string frameName)
        {
            try
            {
                return win.GetType().InvokeMember(
                    frameName, BindingFlags.GetProperty, null, win, null) != null;
            }
            catch
            {
                return false;
            }
        }

        // Resolves a named frame window off the TOP WINDOW.
        //
        // GOTCHA (2026-09-09): this must go through window.frames, NOT
        // document.frames. Reading "frames" off the document object throws a
        // bare COMException E_FAIL on Chameleon's frameset - which is exactly
        // what previously broke pipe-ownership detection and frame access.
        // The primary path here is the same idiom Jumper itself uses in
        // production (top.<frameName> as a property), with window.frames
        // enumeration only as a fallback.
        private static object FindFrameWindowByName(string frameName)
        {
            object topWin = GetTopWindow();
            if (topWin == null) return null;

            try
            {
                object direct = topWin.GetType().InvokeMember(
                    frameName, BindingFlags.GetProperty, null, topWin, null);
                if (direct != null) return direct;
            }
            catch
            {
                // Frameset not loaded yet, or no such frame - fall through.
            }

            try
            {
                object frames = InvokeGet(topWin, "frames");
                if (frames == null) return null;

                int frameCount = Convert.ToInt32(InvokeGet(frames, "length"));
                for (int i = 0; i < frameCount; i++)
                {
                    try
                    {
                        object frameWindow = frames.GetType().InvokeMember(
                            "item", BindingFlags.InvokeMethod, null, frames, new object[] { i });
                        if (frameWindow == null) continue;
                        if (string.Equals(InvokeGet(frameWindow, "name") as string, frameName, StringComparison.Ordinal))
                        {
                            return frameWindow;
                        }
                    }
                    catch
                    {
                        // inaccessible frame - keep looking
                    }
                }
            }
            catch (Exception ex)
            {
                Log($"  -> [frames] window.frames enumeration failed: {ex.Message}");
            }

            return null;
        }

    }
}
